### ISSUE TITLE
[BUG] Output contains Markdown notations

### ISSUE THREAD

**Issue by theoforger** [mayank-Pareek/dev-mate-cli#1]
### Description
With certain language models, the output contains extra Markdown code block notations (```).

### Environment
- **Operating System:** Fedora Workstation 40
- **Node.js Version:** v20.12.2
- **`npm` Version:** 10.5.0
- **Language Model Provider:** Groq

### Content of `.env` File

```
API_KEY=[Redacted]
BASE_URL=https://api.groq.com/openai/v1/
```

### Screenshots

- Command: `npm start ./examples/file.js -- -m llama-3.1-70b-versatile`
  
  ![image](https://github.com/user-attachments/assets/cbdf858b-77c8-45ec-a3da-b52768b54618)

- Command: `npm start ./examples/file.js -- -m gemma2-9b-it`

  ![image](https://github.com/user-attachments/assets/5813e42b-4a4c-4268-8fdf-b082edf222ec)

**Comment by mayank-Pareek** [comment]
Issue has been fixed in pull request #2 .
