### ISSUE TITLE
[BUG] Output file is overwritten if provided multiple input sources

### ISSUE THREAD

**Issue by theoforger** [mayank-Pareek/dev-mate-cli#3]
### Description
When multiple input files are given, output from the last input file overwrites all previous ones

### Environment
- **Operating System:** Fedora Workstation 40
- **Node.js Version:** v20.12.2
- **`npm` Version:** 10.5.0
- **Language Model Provider:** Groq

### Content of `.env` File

```
API_KEY=[Redacted]
BASE_URL=https://api.groq.com/openai/v1/
```

### To Reproduce
Run: 
```bash
npm start ./examples/file.js ./examples/file.py -- --output file-documented.js --model llama-3.1-70b-versatile
``` 

Output:
```
> dev-mate-cli@0.1.0 start
> node dist/index.js ./examples/file.js ./examples/file.py --output file-documented.js --model llama-3.1-70b-versatile

Documented code written to file-documented.js
Documented code written to file-documented.js
```
#### Expected outcome:

Having access to both outputs

#### Actual outcome: 

Only the output from `file.py` is preserved

### Recommended Solutions
- Allow multiple output files
- Concatenate the outputs before writing to file
-  When writing to files, if the specified file isn't empty, create another one

**Comment by mayank-Pareek** [comment]
Resolved bug and merged PR.
